# This workflow is triggered on PR being opened, synced, reopened, closed.
# It dispatches workflow on CompFuzzCI repository, where fuzzing of the PR is handled.

name: Fuzzing on PR
on:
  pull_request_target:
    branches:
      - master
  
jobs:
  FuzzOnPR:
    if: github.event.pull_request.base.ref == 'master' &&
        (github.event.pull_request.author_association == 'COLLABORATOR' ||
        github.event.pull_request.author_association == 'MEMBER' ||
        github.event.pull_request.author_association == 'OWNER')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CompFuzzCI
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'CompFuzzCI',
                  repo: 'DafnyCompilerFuzzer',
                  workflow_id: 'fuzz.yaml',
                  ref: 'main',
                  inputs: {
                      author: '${{github.event.pull_request.user.login}}',
                      branch: '${{github.event.pull_request.head.ref}}',
                      duration: '3600',
                      instance: '2'
                  }
              })