name: BuildImage
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit ID of to build image'
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  BuildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Build, tag, and push docker image to Amazon ECR
        id: build-push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REGISTRY_ALIAS: compfuzzci
          REPOSITORY: compfuzzci-dafny
          IMAGE: ${{github.event.inputs.commit}}
          COMMIT: ${{github.event.inputs.commit}}
        run: |
          max_attempts=5
          attempt=0
          success=false
          while [ $attempt -lt $max_attempts ]; do
            attempt=$((attempt + 1))
            echo "Attempt $attempt of $max_attempts"
            
            docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE -f Docker/dafny.Dockerfile --build-arg COMMIT=$COMMIT . && \
            docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE
            
            if [ $? -eq 0 ]; then
              success=true
              break
            else
              echo "Attempt $attempt failed. Retrying..."
            fi
          done