name: Update Scripts
on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'entrypoint.sh'
permissions:
  id-token: write
  contents: read
jobs:
  UpdateImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Upload all scripts to S3
        run: |
          aws s3 cp entrypoint.sh s3://compfuzzci/evaluation/base-files/
          aws s3 cp scripts/ s3://compfuzzci/evaluation/base-files/scripts/ --recursive

